const DEFAULT_STATE = {
  wakeTime: null,
  sleepTime: null,
  alarm: false,
  alarmTime: null,
  alarmDuration: 60,
  alarmSoundId: "default",
  scenes: ["relax", "bedtime", "energize", "circadian"],
  scene: null,
  lightsNumber: 0,
  sleepSoundVolume: 50,
  sleepSoundDuration: 50,
  lightBrightness: 20,
  lightTone: 70,
  lightsPower: false,
  napEnd: 0,
  napSound: false,
  timerEnd: 0,
  timerLights: false,
  timerSound: false,
  modal: null,
  user: "Joe Smith",
  hotel: "Hilton",
  address: "123 West Street Seattle, WA 98123",
  currentRoomsOccupied: 15,
  currentLightsOn: 12,
  currentAlarmsSet: 5,
  currentAlarmMostUsed: "Music ABC",
  currentLightMostUsed: "10",
  weeklyRoomsOccupied: 68,
  weeklyLightsOn: 50,
  weeklyAlarmsSet: 30,
  weeklyAlarmMostUsed: "Music ABC",
  weeklyLightMostUsed: "8",
  userActions: []
};

export default function reducer(state = DEFAULT_STATE, action) {
  return state;
}
