const DEFAULT_STATE = {
  wakeTime: null,
  sleepTime: null,
  alarm: false,
  alarmTime: null,
  alarmDuration: 60,
  alarmSoundId: "default",
  scenes: ["relax", "bedtime", "energize", "circadian"],
  scene: null,
  lightsNumber: 0,
  sleepSoundVolume: 50,
  sleepSoundDuration: 50,
  lightBrightness: 20,
  lightTone: 70,
  lightsPower: false,
  napEnd: 0,
  napSound: false,
  timerEnd: 0,
  timerLights: false,
  timerSound: false,
  modal: null,
  user: "Joe Smith",
  hotel: "Hilton",
  address: "123 West Street Seattle, WA 98123",
  currentRoomsOccupied: 15,
  currentLightsOn: 12,
  currentAlarmsSet: 5,
  currentAlarmMostUsed: "Music ABC",
  currentLightMostUsed: "10",
  weeklyRoomsOccupied: 68,
  weeklyLightsOn: 50,
  weeklyAlarmsSet: 30,
  weeklyAlarmMostUsed: "Music ABC",
  weeklyLightMostUsed: "8",
  userActions: [],
  rooms: [
    {
      Id: "123AB",
      number: "101",
      sleepTime: "9:30pm",
      wakeTime: "6:00am",
      alarm: "Music AB",
      bulbs: [
        { Id: 1, error: true },
        { Id: 2, error: true },
        { Id: 3, error: true },
        { Id: 4, error: true },
        { Id: 5, error: true },
        { Id: 6, error: true },
        { Id: 7, error: true },
        { Id: 8, error: true },
        { Id: 9, error: true },
        { Id: 10, error: true },
        { Id: 11, error: true },
        { Id: 12, error: true },
        { Id: 13, error: true },
        { Id: 14, error: true },
        { Id: 15, error: true },
        { Id: 16, error: true },
        { Id: 17, error: true },
        { Id: 18, error: true },
        { Id: 19, error: true },
        { Id: 20, error: true },
        { Id: 21, error: true },
        { Id: 22, error: true },
        { Id: 23, error: true },
        { Id: 24, error: true },
        { Id: 25, error: true }
      ],
      schedule: false,
      tabletOn: false
    },
    {
      number: "102",
      Id: "456AB",
      sleepTime: "10:30pm",
      wakeTime: "11:00am",
      alarm: "Music CD",
      bulbs: [
        { Id: 1, error: false },
        { Id: 2, error: true },
        { Id: 3, error: false },
        { Id: 4, error: false },
        { Id: 5, error: false },
        { Id: 6, error: true },
        { Id: 7, error: false },
        { Id: 8, error: false },
        { Id: 9, error: true },
        { Id: 10, error: false },
        { Id: 11, error: false },
        { Id: 12, error: false },
        { Id: 13, error: false },
        { Id: 14, error: true },
        { Id: 15, error: false },
        { Id: 16, error: false },
        { Id: 17, error: false },
        { Id: 18, error: false },
        { Id: 19, error: false },
        { Id: 20, error: false },
        { Id: 21, error: false },
        { Id: 22, error: false },
        { Id: 23, error: false },
        { Id: 24, error: true },
        { Id: 25, error: true }
      ],
      schedule: false,
      tabletOn: false
    },
    {
      number: "102",
      Id: "456AB",
      sleepTime: "10:30pm",
      wakeTime: "11:00am",
      alarm: "Music CD",
      bulbs: [
        { Id: 1, error: false },
        { Id: 2, error: true },
        { Id: 3, error: false },
        { Id: 4, error: false },
        { Id: 5, error: false },
        { Id: 6, error: true },
        { Id: 7, error: false },
        { Id: 8, error: false },
        { Id: 9, error: true },
        { Id: 10, error: false },
        { Id: 11, error: false },
        { Id: 12, error: true },
        { Id: 13, error: false },
        { Id: 14, error: true },
        { Id: 15, error: false },
        { Id: 16, error: false },
        { Id: 17, error: false },
        { Id: 18, error: true },
        { Id: 19, error: false },
        { Id: 20, error: false },
        { Id: 21, error: true },
        { Id: 22, error: false },
        { Id: 23, error: false },
        { Id: 24, error: true },
        { Id: 25, error: true }
      ],
      schedule: false,
      tabletOn: false
    }
  ]
};

export default function reducer(state = DEFAULT_STATE, action) {
  return state;
}
