const DEFAULT_STATE = {
  alerts: null,
  wakeTime: null,
  sleepTime: null,
  minCCT: null,
  maxCCT: null,
  minLevel: null,
  maxLevel: null,
  settingsResetTime: null,
  alarm: false,
  alarmTime: null,
  alarmDuration: 60,
  alarmSoundId: "default",
  scenes: ["relax", "bedtime", "energize", "circadian"],
  scene: null,
  lightsNumber: 0,
  sleepSoundVolume: 50,
  sleepSoundDuration: 50,
  lightBrightness: 20,
  lightTone: 70,
  lightsPower: false,
  napEnd: 0,
  napSound: false,
  timerEnd: 0,
  timerLights: false,
  timerSound: false,
  modal: null,
  user: "Joe Smith",
  address: "123 West Street Seattle, WA 98123",
  currentRoomsOccupied: 15,
  currentLightsOn: 12,
  currentAlarmsSet: 5,
  currentAlarmMostUsed: "Music ABC",
  currentLightMostUsed: "10",
  weeklyRoomsOccupied: 68,
  weeklyLightsOn: 50,
  weeklyAlarmsSet: 30,
  weeklyAlarmMostUsed: "Music ABC",
  weeklyLightMostUsed: "8",
  userActions: [],
  properties: [
    { id: "123", name: "property 1", location: "place" },
    { id: "456", name: "property 2", location: "place" },
    { id: "789", name: "property 3", location: "place" }
  ],
  property: null,
  rooms: [
    {
      propertyId: "123",
      id: "123AB",
      number: "101",
      sleepTime: "9:30pm",
      wakeTime: "6:00am",
      alarm: "Music AB",
      bulbs: [
        { id: 1, error: true },
        { id: 2, error: true },
        { id: 3, error: true },
        { id: 4, error: true },
        { id: 5, error: true },
        { id: 6, error: true },
        { id: 7, error: true },
        { id: 8, error: true },
        { id: 9, error: true },
        { id: 10, error: true },
        { id: 11, error: true },
        { id: 12, error: true },
        { id: 13, error: true },
        { id: 14, error: true },
        { id: 15, error: true },
        { id: 16, error: true },
        { id: 17, error: true },
        { id: 18, error: true },
        { id: 19, error: true },
        { id: 20, error: true },
        { id: 21, error: true },
        { id: 22, error: true },
        { id: 23, error: true },
        { id: 24, error: true },
        { id: 25, error: true }
      ],
      schedule: false,
      tabletOn: false,
      hasIssue: false
    },
    {
      propertyId: "123",
      number: "102",
      id: "456AB",
      sleepTime: null,
      wakeTime: null,
      alarm: { time: null, soundId: null, duration: null },
      sleepSound: { isActive: null, soundId: null, duration: null },
      tablet: { lastHeard: null },
      sensors: {
        temp: null,
        humididty: null,
        lightLevel: null,
        lastMotionTime: null,
        lastMotionMagnititude: null
      },
      bulbs: [
        { id: 1, error: false },
        { id: 2, error: true },
        { id: 3, error: false },
        { id: 4, error: false },
        { id: 5, error: false },
        { id: 6, error: true },
        { id: 7, error: false },
        { id: 8, error: false },
        { id: 9, error: true },
        { id: 10, error: false },
        { id: 11, error: false },
        { id: 12, error: false },
        { id: 13, error: false },
        { id: 14, error: true },
        { id: 15, error: false },
        { id: 16, error: false },
        { id: 17, error: false },
        { id: 18, error: false },
        { id: 19, error: false },
        { id: 20, error: false },
        { id: 21, error: false },
        { id: 22, error: false },
        { id: 23, error: false },
        { id: 24, error: true },
        { id: 25, error: true }
      ],
      schedule: true,
      tabletOn: false
    },
    {
      propertyId: "123",
      number: "102",
      id: "456BC",
      sleepTime: "10:30pm",
      wakeTime: "11:00am",
      alarm: "Music CD",
      bulbs: [
        { id: 1, error: false },
        { id: 2, error: true },
        { id: 3, error: false },
        { id: 4, error: false },
        { id: 5, error: false },
        { id: 6, error: true },
        { id: 7, error: false },
        { id: 8, error: false },
        { id: 9, error: true },
        { id: 10, error: false },
        { id: 11, error: false },
        { id: 12, error: true },
        { id: 13, error: false },
        { id: 14, error: true },
        { id: 15, error: false },
        { id: 16, error: false },
        { id: 17, error: false },
        { id: 18, error: true },
        { id: 19, error: false },
        { id: 20, error: false },
        { id: 21, error: true },
        { id: 22, error: false },
        { id: 23, error: false },
        { id: 24, error: true },
        { id: 25, error: true }
      ],
      schedule: true,
      tabletOn: false
    },
    {
      propertyId: "123",
      number: "102",
      id: "789AB",
      sleepTime: "10:30pm",
      wakeTime: "11:00am",
      alarm: "Music CD",
      bulbs: [
        { id: 1, error: false },
        { id: 2, error: true },
        { id: 3, error: false },
        { id: 4, error: false },
        { id: 5, error: false },
        { id: 6, error: true },
        { id: 7, error: false },
        { id: 8, error: false },
        { id: 9, error: true },
        { id: 10, error: false },
        { id: 11, error: false },
        { id: 12, error: true },
        { id: 13, error: false },
        { id: 14, error: true },
        { id: 15, error: false },
        { id: 16, error: false },
        { id: 17, error: false },
        { id: 18, error: true },
        { id: 19, error: false },
        { id: 20, error: false },
        { id: 21, error: true },
        { id: 22, error: false },
        { id: 23, error: false },
        { id: 24, error: true },
        { id: 25, error: true }
      ],
      schedule: true,
      tabletOn: false
    },
    {
      propertyId: "123",
      number: "102",
      id: "789BC",
      sleepTime: "10:30pm",
      wakeTime: "11:00am",
      alarm: "Music CD",
      bulbs: [
        { id: 1, error: false },
        { id: 2, error: true },
        { id: 3, error: false },
        { id: 4, error: false },
        { id: 5, error: false },
        { id: 6, error: true },
        { id: 7, error: false },
        { id: 8, error: false },
        { id: 9, error: true },
        { id: 10, error: false },
        { id: 11, error: false },
        { id: 12, error: true },
        { id: 13, error: false },
        { id: 14, error: true },
        { id: 15, error: false },
        { id: 16, error: false },
        { id: 17, error: false },
        { id: 18, error: true },
        { id: 19, error: false },
        { id: 20, error: false },
        { id: 21, error: true },
        { id: 22, error: false },
        { id: 23, error: false },
        { id: 24, error: true },
        { id: 25, error: true }
      ],
      schedule: true,
      tabletOn: false
    },
    {
      propertyId: "123",
      id: "123BC",
      number: "101",
      sleepTime: "9:30pm",
      wakeTime: "6:00am",
      alarm: "Music AB",
      bulbs: [
        { id: 1, error: true },
        { id: 2, error: true },
        { id: 3, error: true },
        { id: 4, error: true },
        { id: 5, error: true },
        { id: 6, error: true },
        { id: 7, error: true },
        { id: 8, error: true },
        { id: 9, error: true },
        { id: 10, error: true },
        { id: 11, error: true },
        { id: 12, error: true },
        { id: 13, error: true },
        { id: 14, error: true },
        { id: 15, error: true },
        { id: 16, error: true },
        { id: 17, error: true },
        { id: 18, error: true },
        { id: 19, error: true },
        { id: 20, error: true },
        { id: 21, error: true },
        { id: 22, error: true },
        { id: 23, error: true },
        { id: 24, error: true },
        { id: 25, error: true }
      ],
      schedule: false,
      tabletOn: false
    }
  ]
};

export default function reducer(state = DEFAULT_STATE, action) {
  return state;
}
